env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - airbnb
  - airbnb-typescript
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - react
  - unicorn
rules:
  import/prefer-default-export: 'off'
  react/jsx-filename-extension: [2, { 'extensions': ['.jsx', '.tsx'] }]
  react/require-default-props: 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-floating-promises': 'off'
  unicorn/filename-case: ['error', { 'case': 'kebabCase' }]
  'require-await': 'error'
settings:
  'import/resolver':
    alias:
      map:
        [
          ['~/components', './src/components'],
          ['~/pages', './src/pages'],
          ['~/services', './src/services'],
        ]
      extensions: ['.ts', '.js', '.jsx', '.ts', '.tsx', '.json']
