name: Code Linting
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install modules
        run: pnpm i
      - name: Run ESLint
        run: pnpm run lint
